### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by taoshiyu** [DingZaiHub/ob-decrypt#5]
还原解密函数中...
解密函数还原完成！
开始对象替换，可能稍慢，请耐心等待...
D:\project\ob-decrypt\ob-decrypt.js:347
            arr = init.callee.object.value.split('|');
                                           ^

TypeError: Cannot read property 'split' of undefined
    at D:\project\ob-decrypt\ob-decrypt.js:347:44
    at Array.forEach (<anonymous>)
    at replaceWhile (D:\project\ob-decrypt\ob-decrypt.js:342:20)
    at NodePath._call (C:\Users\ASUS\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (C:\Users\ASUS\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:42:17)
    at NodePath.visit (C:\Users\ASUS\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:101:8)
    at TraversalContext.visitQueue (C:\Users\ASUS\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:116:16)
    at TraversalContext.visitMultiple (C:\Users\ASUS\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:80:17)
    at TraversalContext.visit (C:\Users\ASUS\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:142:19)
    at Function.traverse.node (C:\Users\ASUS\AppData\Roaming\npm\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:82:17)

**Comment by taoshiyu** [comment]
空array会报错

**Comment by taoshiyu** [comment]
加上条件判断后可以过，但是不确定结果是不是正确的

**Comment by UrbanMDR** [comment]
我也遇到了一样的问题
