### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by liangsongliu** [DingZaiHub/ob-decrypt#7]
Waiting for the debugger to disconnect...
F:\ob-decrypt\ob-decrypt.js:77
    decryptStr = decrypt_code[2].declarations[0].id.name
                                             ^

TypeError: Cannot read property '0' of undefined

**Comment by gongqf** [comment]
我也是这个错误，不知道什么原因
D:\ob-decrypt-master\ob-decrypt.js:77
    decryptStr = decrypt_code[2].declarations[0].id.name
                                             ^

TypeError: Cannot read properties of undefined (reading '0')
    at step1 (D:\ob-decrypt-master\ob-decrypt.js:77:46)
    at Object.<anonymous> (D:\ob-decrypt-master\ob-decrypt.js:16:7)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:18:47

Node.js v18.9.1

win10 ltsc 2019
